version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.21.0
      - image: circleci/mongo:3.6
    steps:
      - setup_remote_docker:
          version: 20.10.6
      - checkout
      - run: npm install
      - run: node app.js

workflows:
  workflow1:
    jobs:
      - build
