version: 2.1

jobs:
  build:
    environment:
      ENV: test
    docker:
      - image: circleci/node:12.21.0
      - image: circleci/mongo:3.6
      - image: cimg/redis:6.2.6
    resource_class: medium
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - run: npm install
      - run: node app.js

workflows:
  workflow1:
    jobs:
      - build
