
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.21.0
      - image: circleci/mongo@sha256:5d8ab3f01299232b05d2d7ba46ff0ee7b0d7adbcb8e55f30b9fe9d8145fcbb96
    steps:
      - setup_remote_docker:
          version: 20.10.6
      - checkout
      - run: npm install
      - run: node app.js

workflows:
  workflow1:
    jobs:
      - build
